### ISSUE TITLE
Safari + Firefox not rendering JS in head

### ISSUE THREAD

**Issue by zakelfassi** [imadarchid/voipdownWordpress#1]
It seems that putting the JS in the head section on Firefox/Safari doesn't do good (eg. sporton.ma)
Maybe switching the false here https://github.com/VoIPDown/voipdownWordpress/blob/master/public/class-voip-down-maroc-public.php#L99 to true would do the trick?

**Comment by imadarchid** [comment]
I tested it on Firefox but it's working fine (http://servphp1-archid.rhcloud.com).
I think it'll do the trick ! (and it's better that it gets included in the body section like you've said).

**Comment by zakelfassi** [comment]
Not sure if you're using an updated version, but the voipdownJS on servphp1\* is loaded inside the body.

**Comment by imadarchid** [comment]
Sorry, I just changed it to "true" to test if everything works. I'll update the plugin anyway.

**Comment by imadarchid** [comment]
- Updated the plugin in WP repo.
- Updated the plugin on Github.
  Thanks !
